export const homeUrl = '/'
export const loginUrl='/login'
export const signupUrl='/signup'
export const orgUrl = '/organization'
export const orgCompleteUrl = '/complete'
export const dashboardUrl = '/dashboard'
export const addPayeeUrl = '/add-payee'
export const managePayeeUrl = '/manage-payee'